## Put comments here that give an overall description of what your
## functions do: The function makeCacheMatrix takes the matrix from the global
## environment, caches the inverse if solved and creates a list of functions. 
## The second function, cacheSolve, takes the list generated by makeCacheMatrix
##solves for the inverse of the matrix, first by checking if it is cached, 
##and the matricies are the same. If the inverse is not cached, it will solve for it
##and set cache the inverse of the matrix

## Function below takes in matrix and creates list. Please note this function does
##not solve for the inverse. Run this function first and store the created list
##as a different variable in the global environment

makeCacheMatrix <- function(x = matrix) #passes in a matrix called x
{
      inverse <- NULL
      set <- function(y) #sets the matrix
      {
            x <<- y
            inverse <<- NULL
      }
      get <- function() x #gets the matrix 
      SetInverse <- function(a) inverse <<- a #sets the inverse
      getInverse <- function() inverse #sends the inverse 
      
      list(set = set, get = get, SetInverse = SetInverse, getInverse = getInverse) #defines list 
      
}

## Takes in the list defined from the above function. Checks to see if solution 
##is cached. If not chached, it will solve and set the cache. Send this function
##the list that was created before. 


cacheSolve <- function(x, ...) ##Takes in List
{
      
      i <- x$getInverse() #pulls the inverse from the list
      if(!is.null(i)) #checks if the inverse has been created already
      {
            print("Getting cached matrix inverse!")
            return(i)
      }
      
      MatrixToInverse <- x$get() #goes if inverse has not been created. Pulls the matrix from list
      i <- solve(MatrixToInverse) #inverts matrix
      x$SetInverse(i) #caches the inverse
      i #returning inverse of x
}
